### ISSUE TITLE
window is not defined when SSR

### ISSUE THREAD

**Issue by romanown** [ganlanyuan/tiny-slider#631]
__Issue description__:  
ReferenceError: window is not defined
    at /var/www/dev/desktop/node_modules/tiny-slider/dist/tiny-slider.js:2:11
    at Object.<anonymous> (/var/www/dev/desktop/node_modules/tiny-slider/dist/tiny-slider.js:3208:3)

__Demo link/slider setting__:   

_Tiny-slider version_:   2.9.3
_Browser name && version_:  
_OS name && version_:   
I use server side rendering on node.js + react.js.
import { tns } from 'tiny-slider';

**Comment by romanown** [comment]
can You apply this changes? [https://github.com/ganlanyuan/tiny-slider/pull/479](https://github.com/ganlanyuan/tiny-slider/pull/479) it helped me for server side rendering, but i can not import.

**Comment by bmediax** [comment]
I used https://github.com/gregberge/loadable-components to load it up and it to work for building

**Comment by mlaigre** [comment]
Thanks @bmediax, inspired by the lib you point out I solved my issue using a dynamic import

```ts
useEffect(() => {
    import('tiny-slider').then(({ tns }) => {
        tns(options)
    })
}, [])
```

**Comment by ALWISHARIFF** [comment]
Dear Team
I am getting a page flicker when i import using useEffect hook i hope this issue will be fixed any collaborations i can help with.
Thank you

**Comment by tytanus97** [comment]
in angular SSR, for me what worked was:
```javascript
import('tiny-slider').then((module) => {
      const { tns } = module.default;
      tns();
});
```
