### ISSUE TITLE
Uncaught DOMException: Failed to execute 'appendChild' on 'Node': Only one element on document allowed.

### ISSUE THREAD

**Issue by rommelvisuals** [ganlanyuan/tiny-slider#767]
__Issue description__:  
Uncaught DOMException: Failed to execute 'appendChild' on 'Node': Only one element on document allowed.

__Demo link/slider setting__:   
  var slider = tns({
    "container": ".testimonial-slider",
    "items": 2,
    "slideBy": "1",
    "mouseDrag": true,
    "swipeAngle": false,
    "speed": 400,
    "controls": false,
    "autoplay": true,
    "autoplayHoverPause": false,
    "autoplayTimeout": 10000,
    "autoplayButtonOutput" : false,
    "nav": true,
    "navPosition": '',
  });

_Tiny-slider version_:   Version 2
_Browser name && version_:  Google Chrome Version 100.0.4896.88
_OS name && version_:   Windows 10

**Comment by rommelvisuals** [comment]
jquery-3.6.0.min.js:2 Uncaught DOMException: Failed to execute 'appendChild' on 'Node': Only one element on document allowed.
    at t (https://cdnjs.cloudflare.com/ajax/libs/tiny-slider/2.9.2/min/tiny-slider.js:1:16602)
    at t (https://cdnjs.cloudflare.com/ajax/libs/tiny-slider/2.9.2/min/tiny-slider.js:1:16676)
    at t (https://cdnjs.cloudflare.com/ajax/libs/tiny-slider/2.9.2/min/tiny-slider.js:1:16676)
    at t (https://cdnjs.cloudflare.com/ajax/libs/tiny-slider/2.9.2/min/tiny-slider.js:1:16676)
    at t (https://cdnjs.cloudflare.com/ajax/libs/tiny-slider/2.9.2/min/tiny-slider.js:1:16676)
    at t (https://cdnjs.cloudflare.com/ajax/libs/tiny-slider/2.9.2/min/tiny-slider.js:1:16676)
    at t (https://cdnjs.cloudflare.com/ajax/libs/tiny-slider/2.9.2/min/tiny-slider.js:1:16676)
    at fn (https://cdnjs.cloudflare.com/ajax/libs/tiny-slider/2.9.2/min/tiny-slider.js:1:16692)
    at aa (https://cdnjs.cloudflare.com/ajax/libs/tiny-slider/2.9.2/min/tiny-slider.js:1:7973)
    at tinySlider (https://cdn.shopify.com/s/files/1/0006/4559/5251/t/9/assets/main.js?v=11892999402349269010:1:142)
(anonymous) @ jquery-3.6.0.min.js:2
setTimeout (async)
S.readyException @ jquery-3.6.0.min.js:2
(anonymous) @ jquery-3.6.0.min.js:2
e @ jquery-3.6.0.min.js:2
t @ jquery-3.6.0.min.js:2
setTimeout (async)
(anonymous) @ jquery-3.6.0.min.js:2
c @ jquery-3.6.0.min.js:2
fireWith @ jquery-3.6.0.min.js:2
fire @ jquery-3.6.0.min.js:2
c @ jquery-3.6.0.min.js:2
fireWith @ jquery-3.6.0.min.js:2
t @ jquery-3.6.0.min.js:2
setTimeout (async)
(anonymous) @ jquery-3.6.0.min.js:2
c @ jquery-3.6.0.min.js:2
fireWith @ jquery-3.6.0.min.js:2
fire @ jquery-3.6.0.min.js:2
c @ jquery-3.6.0.min.js:2
fireWith @ jquery-3.6.0.min.js:2
ready @ jquery-3.6.0.min.js:2
B @ jquery-3.6.0.min.js:2

**Comment by rommelvisuals** [comment]
How to fix this please?

**Comment by julien-mamalian** [comment]
We have the same issue here. It seems the solution in previous threads as been removed in 2.9.4 version?

**Comment by julien-mamalian** [comment]
Guess this is related to:
#661
